spring:
  application:
    name: UserProvider
  datasource:
    url: jdbc:mysql://localhost:3306/0909?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


server:
  port: 9009

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka,http://localhost:9999/eureka
